### PR TITLE
fix(build): handle properly the string

### PR DESCRIPTION
**Pull request by Helias**

### CODE REVIEW

**Comment by Nefertumm** [comment]
Fixed in #2

**Comment by Helias** [comment]
@Nefertumm what about merge your PR and close this?

**Comment by Nefertumm** [comment]
Still have to do some things, that's why it's not merged yet :D

**Comment by BarbzYHOOL** [comment]
dso this is a duplicate fix?

**Comment by Helias** [comment]
Yes, I think so, I am closing this, if we need to add/improve something I think we can use the other opened PR.

**Pull request closed without merging**
